myapp/store/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, \
    IntegerField, SelectField
from wtforms.validators import ValidationError, DataRequired
from myapp.models import Product


class ProductForm(FlaskForm):
    """
    Form for admin to add or delete a product
    """
    #    product = FormField(ProductForm)
    name = StringField('Product Name', validators=[DataRequired()])
    description = StringField('Product Description',
                              validators=[DataRequired()])
    # image = check file upload for flask-form
    category = SelectField('Category', coerce=int)
    weight = IntegerField('Weight (grams)', validators=[DataRequired()])
    submit = SubmitField('Submit')

    def validate_name(self, name):
        product = Product.query.filter_by(name=name.data).first()
        if product is not None:
            raise ValidationError('Product name already in use. \
                    Please use a different one.')


# class CreateNewProductForm(FlaskForm):
#     #    product = FormField(ProductForm)
#     name = StringField('Product Name', validators=[DataRequired()])
#     description = StringField('Product Description',
#                               validators=[DataRequired()])
#     # image = check file upload for flask-form
#     category = SelectField('Category', coerce=int)
#     weight = IntegerField('Weight (grams)', validators=[DataRequired()])
#     submit = SubmitField('Create Product')
#
#     def validate_name(self, name):
#         product = Product.query.filter_by(name=name.data).first()
#         if product is not None:
#             raise ValidationError('Product name already in use. \
#                     Please use a different one.')
#
#
# class EditProductForm(FlaskForm):
#     name = StringField('Product Name', validators=[DataRequired()])
#     description = StringField('Product Description',
#                               validators=[DataRequired()])
#     # image = check file upload for flask-form
#     category = SelectField('Category', coerce=int)
#     weight = IntegerField('Weight (grams)', validators=[DataRequired()])
#     submit = SubmitField('Update Product')
#
#     def __init__(self, original_specs, *args, **kwargs):
#         super(EditProductForm, self).__init__(*args, **kwargs)
#         # original product specs saved as instance variables
#         self.original_name = original_specs.name
#
#     def validate_name(self, name):
#         if name.data != self.original_name:
#             product = Product.query.filter_by(
#                 name=self.name.data).first()
#             if product is not None:
#                 raise ValidationError('Product name already in use. \
#                         Please use a different one.')

myapp/store/__init__.py
from flask import Blueprint

bp = Blueprint('store', __name__)

from myapp.store import routes

myapp/store/routes.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required
from myapp.models import Product, ProductCategory
from myapp.store import bp
from myapp.store.forms import ProductForm
from myapp import db
from myapp.decorators import admin_required, permission_required
from flask_login import current_user


@bp.route('/')
def store():
    # get all products and present them
    products = Product.query.all()
    admin = current_user.is_admin()
    return render_template('store/index.html',
                           title='Store', products=products, admin=admin)


@bp.route('/add', methods=['GET', 'POST'])
@login_required
@admin_required
def add_product():
    """
    Add a new product to the database
    """
    categories = ProductCategory.query.order_by('name')
    form = ProductForm()
    form.category.choices = [(c.id, c.name) for c in categories]
#     if request.method == 'POST':
#         category = ProductCategory.query.filter_by(
#                 id=form.category.data).first()
#         return 'Name: {}, Category: {}'.format(form.name.data, category.name)
    if form.validate_on_submit():
        category = ProductCategory.query.filter_by(
            id=form.category.data).first()
        product = Product(
            name=form.name.data,
            description=form.description.data,
            # image=form.image.data,
            # Create a method to make a thumbnail from a full image?
            # thumbnail=
            # Not sure about how to add category to a new product
            category=category,
            weight=form.weight.data)
        db.session.add(product)
        db.session.commit()
        flash('Your product has been added!')
        return redirect(url_for('store.store'))
    return render_template('store/crud_product.html',
                           form=form, title='Add Product')


@bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@admin_required
def edit_product(id):
    """
    Edit a product stored in database
    """
    product = Product.query.get_or_404(id)
    current_category = product.category
    categories = ProductCategory.query.all()
    # 1. Remove current product category from full list
    for c in categories:
        if c == current_category:
            categories.remove(c)
    # Sort list alphabetically

    categories.sort(key=lambda x: x.name)

    # 3. Prepend categories with the current category of the product
    categories.insert(0, current_category)

    form = ProductForm(obj=product)
    form.category.choices = [(c.id, c.name) for c in categories]
#     if request.method == 'POST':
#         category = ProductCategory.query.filter_by(
#                 id=form.category.data).first()
#         return 'Name: {}, Category: {}'.format(form.name.data, category.name)
    if form.validate_on_submit():
        category = ProductCategory.query.filter_by(
            id=form.category.data).first()
        product.name = form.name.data,
        product.description = form.description.data,
        # image=form.image.data,
        # Create a method to make a thumbnail from a full image?
        # thumbnail=
        # Not sure about how to add category to a new product
        product.category = category,
        product.weight = form.weight.data
        db.session.commit()
        flash('Your product has been updated!')
        return redirect(url_for('store.store'))
    form.name.data = product.name
    form.description.data = product.description
    form.category.data = product.category
    form.weight.data = product.weight
    return render_template('store/crud_product.html',
                           form=form, product=product,
                           title='Update Product')


@bp.route('/delete/<id>', methods=['GET', 'POST'])
@login_required
@admin_required
def delete_product(id):
    """
    Delete a product from the database
    """
    product = Product.query.get_or_404(id)
    db.session.delete(product)
    db.session.commit()
    flash('You have successfully deleted this product')

    return redirect(url_for('store.store'))

    return render_template('crud_product.html', title='Delete Product')

myapp/templates/store/crud_product.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <h1 class="is-size-4">{{ title }}</h1>
        {% from "shared/_macros.html" import render_field %}
        <form action="" method=post class="form">
            {{ form.hidden_tag() }}
            <dl>
                {{ render_field(form.name, class="input", placeholder="Enter product name") }}
                {{ render_field(form.description, class="input", placeholder="Enter description") }}
                {{ render_field(form.category, class="input") }}
                {{ render_field(form.weight, class="input", placeholder="Enter weight in grams") }}
                <div class="is-flex">
                    {{ render_field(form.submit, class="button is-link") }}
                    <div class="control">
                        <a href="{{ url_for('store.store') }}" class="button is-warning">Cancel</a>
                    </div>
                </div>
            </dl>
        </form>
    </div>
{% endblock %}

myapp/templates/store/index.html
{% extends "base.html" %}

{% block content %}
    <section>
        <section class="hero is-primary">
            <div class="hero-body">
                <div class="container">
                    <h1 class="title">
                        Our goods
                    </h1>
                    <h2 class="subtitle">
                        ...Baked with love
                    </h2>
                </div>
            </div>
        </section>
        
        {% if admin %}
        <section class="container store-admin">
            <a href="{{ url_for('store.add_product') }}" class="button is-success">Add Product</a> 
        </section>
        {% endif %}
        
        <section class="container products">
            {% if products %}
                {% for product in products %}
                    {% include "shared/_product.html" ignore missing %}
                {% endfor %}
            {% endif %}
        </section>

    </section>
{% endblock %}